# Generated by Django 3.2.4 on 2021-06-04 10:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='title')),
            ],
            options={
                'verbose_name': 'services time',
                'verbose_name_plural': 'service prices',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='price')),
                ('position', models.CharField(max_length=20, verbose_name='position')),
                ('best_for', models.CharField(max_length=30, verbose_name='best_for')),
                ('benefits', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='benefits')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time', to='services.servicetimemodel', verbose_name='time')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
