# Generated by Django 3.2.4 on 2021-06-04 10:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='benefits_en_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='benefits'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='benefits_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='benefits'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='benefits_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='benefits'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='best_for_en_us',
            field=models.CharField(max_length=30, null=True, verbose_name='best_for'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='best_for_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='best_for'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='best_for_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='best_for'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='position_en_us',
            field=models.CharField(max_length=20, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='position_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='position_uz',
            field=models.CharField(max_length=20, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='servicetimemodel',
            name='title_en_us',
            field=models.CharField(max_length=10, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicetimemodel',
            name='title_ru',
            field=models.CharField(max_length=10, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicetimemodel',
            name='title_uz',
            field=models.CharField(max_length=10, null=True, verbose_name='title'),
        ),
    ]
