# Generated by Django 3.2.4 on 2021-06-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210604_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='time',
            field=models.CharField(max_length=20, verbose_name='time'),
        ),
        migrations.DeleteModel(
            name='ServiceTimeModel',
        ),
    ]
