# Generated by Django 3.2.4 on 2021-06-03 08:14

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='author images')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('name_en_us', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='BlogTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('name_en_us', models.CharField(max_length=15, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=15, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=15, null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('name_en_us', models.CharField(max_length=20, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=20, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=20, null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_en_us', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('short_description', models.CharField(max_length=200, verbose_name='short_description')),
                ('short_description_en_us', models.CharField(max_length=200, null=True, verbose_name='short_description')),
                ('short_description_uz', models.CharField(max_length=200, null=True, verbose_name='short_description')),
                ('short_description_ru', models.CharField(max_length=200, null=True, verbose_name='short_description')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='long_description')),
                ('long_description_en_us', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description')),
                ('long_description_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description')),
                ('long_description_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='blog.authormodel', verbose_name='author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='blog.categorymodel', verbose_name='categories')),
                ('tags', models.ManyToManyField(related_name='blogs', to='blog.BlogTagModel', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='BlogImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog images')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogmodel', verbose_name='blog')),
            ],
            options={
                'verbose_name': 'blog image',
                'verbose_name_plural': 'blog images',
            },
        ),
    ]
