# Generated by Django 3.2.4 on 2021-06-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='description_en_us',
            field=models.CharField(max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='description_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='description_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='description'),
        ),
    ]
