# Generated by Django 3.2.4 on 2021-06-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210603_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='description_en_us',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
