# Generated by Django 3.2.4 on 2021-06-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210603_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='blog.CategoryModel', verbose_name='categories'),
        ),
    ]
