# Generated by Django 3.2.4 on 2021-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210603_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='linked',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='linked'),
        ),
        migrations.AddField(
            model_name='authormodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='twitter'),
        ),
    ]
