# Generated by Django 3.2.4 on 2021-06-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogmodel', verbose_name='blog'),
        ),
    ]
