# Generated by Django 3.2.4 on 2021-06-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200, verbose_name='feedback')),
                ('feedback_en_us', models.CharField(max_length=200, null=True, verbose_name='feedback')),
                ('feedback_uz', models.CharField(max_length=200, null=True, verbose_name='feedback')),
                ('feedback_ru', models.CharField(max_length=200, null=True, verbose_name='feedback')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('name_en_us', models.CharField(max_length=20, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=20, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=20, null=True, verbose_name='name')),
                ('job', models.CharField(max_length=20, verbose_name='job')),
                ('job_en_us', models.CharField(max_length=20, null=True, verbose_name='job')),
                ('job_uz', models.CharField(max_length=20, null=True, verbose_name='job')),
                ('job_ru', models.CharField(max_length=20, null=True, verbose_name='job')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
            },
        ),
    ]
