# Generated by Django 3.2.4 on 2021-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial', verbose_name='image'),
        ),
    ]
