# Generated by Django 3.2.4 on 2021-06-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='image')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_en_us', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_en_us', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolio',
            },
        ),
    ]
