# Generated by Django 3.2.4 on 2021-06-03 06:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='full_title',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='full_title'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='twitter'),
        ),
        migrations.CreateModel(
            name='PortfolioImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='image')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfoliomodel', verbose_name='portfolio')),
            ],
            options={
                'verbose_name': 'portfolio image',
                'verbose_name_plural': 'portfolio images',
            },
        ),
    ]
