# Generated by Django 3.2.4 on 2021-06-03 06:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210603_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='description_en_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='full_title_en_us',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='full_title'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='full_title_ru',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='full_title'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='full_title_uz',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='full_title'),
        ),
    ]
