# Generated by Django 3.2.4 on 2021-06-05 15:14

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='image')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_en_us', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_en_us', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('description_en_us', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description')),
                ('solution', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='solution')),
                ('solution_en_us', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='solution')),
                ('solution_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='solution')),
                ('solution_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='solution')),
                ('full_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='full_title')),
                ('full_title_en_us', models.CharField(blank=True, max_length=80, null=True, verbose_name='full_title')),
                ('full_title_uz', models.CharField(blank=True, max_length=80, null=True, verbose_name='full_title')),
                ('full_title_ru', models.CharField(blank=True, max_length=80, null=True, verbose_name='full_title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='course video', verbose_name='video')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='menu.coursemodel', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course video',
                'verbose_name_plural': 'course videos',
            },
        ),
    ]
